title: Revival
description: >- # this means to ignore newlines until "baseurl:"
  Mackenzie's 2020-2021 Yearbook
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# include:
#   - _pages

defaults:
  - scope:
      path: ""
    values:
      layout: default

collections_dir: /pages/

collections:
  academics:
    output: true
    permalink: /:collection/:name/
  clubs:
    output: true
    permalink: /:collection/:name/
  events:
    output: true
    permalink: /:collection/:name/

# header_pages:
#   - "_pages/music.html"
#   - "_pages/athletics.html"
#   - "_pages/student-work.html"

plugins:
  - jekyll-seo-tag
